server:
  port: 8086

logging:
  level:
    org.springframework.security: debug

security:
  oauth2:
    client:
      client-id: client-application
  ignored: /**

logger-interceptor:
  application-name: client-by-implict-grant
  excluded-uri-patterns: /bootstrap.min.css, /favicon.ico