server:
  port: 8080

logging:
  level:
    org.springframework.security: debug

logger-interceptor:
  application-name: authorization-server
  excluded-uri-patterns: /bootstrap.min.css, /favicon.ico
