server:
  port: 8084

logging:
  level:
    org.springframework.security: debug

security:
  oauth2:
    client:
      client-id: client-application
      client-secret: secret
      grant-type: client_credentials
      access-token-uri: http://localhost:8080/oauth/token
  ignored: /**
